kafili/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from kafili import settings
from orphanage.views import home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^orphanage/', include('orphanage.urls', namespace="orphanage")),
    url('^$', home),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'orphanage.views.handler_404'
handler500 = 'orphanage.views.handler_500'
handler403 = 'orphanage.views.handler_403'

orphanage/urls.py
from django.conf.urls import url
from wkhtmltopdf.views import PDFTemplateView

from orphanage.views import *

app_name = 'orphanage'

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', connexion, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^request_registration/$', request_registration, name='request_registration'),
    url(r'^profile/$', profile, name='profile'),

    # Children
    url(r'^children/$', children, name='children'),
    url(r'^children/insert/$', child_insert, name='child_insert'),
    url(r'^children/print_cards/$', StudentCardPDF.as_view(), name='print_cards'),
    url(r'^children/(?P<child_id>[0-9]+)/$', child_details, name='child_details'),
    url(r'^children/(?P<child_id>[0-9]+)/print_card/$', StudentCardPDF.as_view(), name='print_card'),
    url(r'^children/(?P<child_id>[0-9]+)/update/$', child_update, name='child_update'),
    
    # Guardians
    # url(r'^guardians/$', guardians, name='guardians'),
    # url(r'^guardians/(?P<guardian_id>[0-9]+)/$', guardian_details, name='guardian_details'),
    # url(r'^guardians/(?P<guardian_id>[0-9]+)/update/$', guardian_update, name='guardian_update'),
    # url(r'^guardians/insert/$', guardian_insert, name='guardian_insert'),
    
    # Years
    url(r'^year/$', year_details, name='year_details'),
    url(r'^year/insert/$', year_insert, name='year_insert'),
    url(r'^year/switch/(?P<year>[0-9]{4})/$', year_switch, name='year_switch'),
    
    # Grades
    url(r'^grades/$', grades, name='grades'),
    url(r'^grades/(?P<grade_id>[0-9]+)/$', grade_details, name='grade_details'),
    url(r'^grades/(?P<grade_id>[0-9]+)/update/$', grade_update, name='grade_update'),
    url(r'^grades/insert/$', grade_insert, name='grade_insert'),

    # Students
    url(r'^grades/(?P<grade_id>[0-9]+)/students/$', students, name='students'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/insert/$', student_insert, name='student_insert'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/print_cards/$', StudentCardPDF.as_view(), name='print_cards'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/$', student_details, name='student_details'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/print_card/$', StudentCardPDF.as_view(), name='print_card'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/update/$', student_update, name='student_update'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/marks/$', student_marks, name='student_marks'),

    # Website
    # url(r'^grades/(?P<grade_id>[0-9]+)/subjects/insert/$', subject_insert, name='subject_insert'),

]

orphanage/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import logout as django_logout

from orphanage.forms import ConnectionForm, ChildForm
from orphanage.models import Child


def connexion(request):
    user = request.user if request.user.is_authenticated else None
    if request.method == 'POST':
        form = ConnectionForm(request.POST)
        if not user:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
        if user and user.is_active:
            login(request, user)
            url = request.GET.get('next') if 'next' in request.GET else reverse('orphanage:home')
            return redirect(url)
    else:
        form = ConnectionForm()

    return render(request, 'orphanage/login.html', {
        'form': form,
    })


def logout(request):
    django_logout(request)
    return redirect(reverse('orphanage:login'))


@login_required
def profile(request):

    return render(request, 'orphanage/profile.html')


@login_required
def children_list(request):
    children = Child.list()

    number_per_page = 20
    next_page = None
    previous_page = None

    paginator = Paginator(children, number_per_page)
    if request.GET.get('page'):
        page = request.GET.get('page')
    else:
        page = 1
    try:
        orphans_page = paginator.page(page)
    except PageNotAnInteger:
        orphans_page = paginator.page(1)
    except EmptyPage:
        orphans_page = paginator.page(paginator.num_pages)

    if orphans_page.has_next():
        next_page = orphans_page.next_page_number()
    if orphans_page.has_previous():
        previous_page = orphans_page.previous_page_number()

    context = {
        'items': orphans_page,
        'number_per_page': number_per_page,
        'page': page,
        'number_of_pages': paginator.num_pages,
        'range': paginator.page_range,
        'next_page': next_page,
        'previous_page': previous_page,
    }

    return render(request, 'orphanage/children_list.html', context)


@login_required
def child_details(request, id):
    child = Child.objects.get(pk=id)

    context = {
        'child': child,
    }

    return render(request, 'orphanage/child_details.html', context)


@login_required
def child_insert(request):
    
    form = ChildForm()

    context = {
        'form': form
    }

    return render(request, 'orphanage/child_update.html', context)


@login_required
def child_update(request, id):

    try:
        child = Child.objects.get(id=id)
    except ObjectDoesNotExist:
        return Http404()

    if request.method == 'POST':
        form = ChildForm(data=request.POST, files=request.FILES, instance=child)
        if form.is_valid():
            form.instance.birthday = form.cleaned_data['birthday']
            form.instance.save()
            return redirect(reverse('orphanage:child_details', args=[child.id]))
    else:
        form = ChildForm(instance=child, initial={'birthday': child.birthday})

    context = {
        'form': form,
    }

    return render(request, 'orphanage/child_update.html', context)

orphanage/views/child_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from orphanage import settings as orphanage_settings
from orphanage.decorators import valid_session
from orphanage.forms import ChildForm, ChildFilterForm
from orphanage.models import Child


@login_required
@valid_session
def children(request):

    qset = Child.list(**request.GET)

    table_size = orphanage_settings.TABLE_SIZE
    if 'tablesize' in request.GET:
        try:
            tmp_table_size = int(request.GET['tablesize'])
            if tmp_table_size > 0:
                table_size = tmp_table_size
        except ValueError:
            pass
    next_page = None
    previous_page = None

    paginator = Paginator(qset, table_size)
    if request.GET.get('page'):
        page = request.GET.get('page')
    else:
        page = 1
    try:
        orphans_page = paginator.page(page)
    except PageNotAnInteger:
        orphans_page = paginator.page(1)
    except EmptyPage:
        orphans_page = paginator.page(paginator.num_pages)

    if orphans_page.has_next():
        next_page = orphans_page.next_page_number()
    if orphans_page.has_previous():
        previous_page = orphans_page.previous_page_number()

    initial_dict = {}
    for key in request.GET.keys():
        if request.GET[key]:
            initial_dict[key] = request.GET[key]

    # POST METHOD
    if request.method == 'POST':
        if request.POST.get('action', '') == 'delete_multiple':
            children = Child.objects.filter(pk__in=request.POST.getlist('objects_ids', ''))
            res, message = Child.delete_children(children)
            if res:
                messages.success(request, message)
            else:
                messages.error(request, message)
            return redirect(reverse('orphanage:children'))
        elif request.POST.get('action', '') == 'import_pictures':
            res, message, err_msg = Child.import_photos()
            messages.success(request, message)
            if err_msg:
                messages.warning(request, err_msg)
            return redirect(reverse('orphanage:children'))

    context = {
        'items': orphans_page,
        'table_size': table_size,
        'page': page,
        'filter_form': ChildFilterForm(initial=initial_dict),
        'number_of_pages': paginator.num_pages,
        'range': paginator.page_range,
        'next_page': next_page,
        'previous_page': previous_page,
        'page_title': 'Children',
        'page_title_ar': 'لائحة الأطفال'
    }

    return render(request, 'orphanage/child/children_list.html', context)


@login_required
@valid_session
def child_insert(request):
    
    if request.method == 'POST':
        form = ChildForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.instance.birthday = form.cleaned_data['birthday']
            form.instance.save()
            child_title = 'الطفل' if form.instance.sex == 'm' else 'الطفلة'
            messages.success(request, 'تمت إضافة ' + child_title + ' بنجاح.')
            return redirect(reverse('orphanage:child_details', args=[form.instance.id]))
        messages.error(request, 'المرجو مراجعة بيانات الطفل(ة)')
    else:
        form = ChildForm()

    context = {
        'form': form,
        'page_title': 'Child insert',
        'page_title_ar': f'إضافة تلميذ(ة)'
    }

    return render(request, 'orphanage/child/child_update.html', context)


@login_required
@valid_session
def child_details(request, child_id):
    
    child = get_object_or_404(Child, id=child_id)
    child_title = 'الطفل' if child.sex == 'm' else 'الطفلة'

    if request.method == 'POST':
        if request.POST['action'] == 'delete':
            child.delete()
            return redirect(reverse('orphanage:children'))

    context = {
        'child': child,
        'page_title': 'Child details',
        'page_title_ar': f'بيانات {child_title} {child}'
    }

    return render(request, 'orphanage/child/child_details.html', context)


@login_required
@valid_session
def child_update(request, child_id):

    child = get_object_or_404(Child, id=child_id)

    if request.method == 'POST':
        form = ChildForm(data=request.POST, files=request.FILES, instance=child)
        if form.is_valid():
            form.instance.birthday = form.cleaned_data['birthday']
            form.instance.save()
            child_title = 'الطفل' if child.child.sex == 'm' else 'الطفلة'
            messages.success(request, 'تمت عملية تحديث بيانات ' + child_title + ' بنجاح.')
            return redirect(reverse('orphanage:child_details', args=[child.id]))
        messages.error(request, f'المرجو مراجعة بيانات الطفل(ة) {form.errors}')
    else:
        form = ChildForm(instance=child, initial={'birthday': child.birthday})

    context = {
        'form': form,
        'page_title': 'Child update',
        'page_title_ar': f'تحديث بيانات الأطفال {child}'
    }

    return render(request, 'orphanage/child/child_update.html', context)


@login_required
@valid_session
def child_marks(request, child_id):
    
    child = get_object_or_404(Child, id=child_id)

    if request.method == 'POST':
        if request.POST['action'] == 'delete':
            child.delete()
            return redirect(reverse('orphanage:children'))

    context = {
        'child': child,
        'page_title': 'Child marks',
        'page_title_ar': f'علامات الأطفال {child}'
    }

    return render(request, 'orphanage/child/child_marks.html', context)

orphanage/views/error_handlers.py
from django.shortcuts import render_to_response


def handler_404(request, exception):
    template_name = 'orphanage/errors/404.html'
    response = render_to_response(template_name)
    response.status_code = 404
    return response


def handler_500(request):
    template_name = 'orphanage/errors/500.html'
    response = render_to_response(template_name)
    response.status_code = 500
    return response


def handler_403(request, exception):  # permission denied
    template_name = 'orphanage/errors/403.html'
    response = render_to_response(template_name)
    response.status_code = 403
    return response

orphanage/views/printing.py
from django.contrib import messages
from django.http import Http404
from django.template.response import TemplateResponse

from wkhtmltopdf.views import PDFTemplateView, PDFTemplateResponse

from orphanage.models import Student

# import os
# from django.conf import settings
# from django.http import HttpResponse
# from django.template import Context
# from django.template.loader import get_template
# from xhtml2pdf import pisa
#
#
# def link_callback(uri, rel):
#     """
#     Convert HTML URIs to absolute system paths so xhtml2pdf can access those
#     resources
#     """
#     # use short variable names
#     sUrl = settings.STATIC_URL      # Typically /static/
#     sRoot = settings.STATIC_ROOT    # Typically /home/userX/project_static/
#     mUrl = settings.MEDIA_URL       # Typically /static/media/
#     mRoot = settings.MEDIA_ROOT     # Typically /home/userX/project_static/media/
#
#     # convert URIs to absolute system paths
#     if uri.startswith(mUrl):
#         path = os.path.join(mRoot, uri.replace(mUrl, ""))
#     elif uri.startswith(sUrl):
#         path = os.path.join(sRoot, uri.replace(sUrl, ""))
#     else:
#         return uri  # handle absolute uri (ie: http://some.tld/foo.png)
#
#     # make sure that file exists
#     if not os.path.isfile(path):
#             raise Exception(
#                 'media URI must start with %s or %s' % (sUrl, mUrl)
#             )
#     return path
#
#
# def render_pdf_view(request):
#     template_path = 'user_printer.html'
#     context = {'myvar': 'this is your template context'}
#     # Create a Django response object, and specify content_type as pdf
#     response = HttpResponse(content_type='application/pdf')
#     response['Content-Disposition'] = 'attachment; filename="report.pdf"'
#     # find the template and render it.
#     template = get_template(template_path)
#     html = template.render(Context(context))
#
#     # create a pdf
#     pisaStatus = pisa.CreatePDF(
#        html, dest=response, link_callback=link_callback)
#     # if error then show some funy view
#     if pisaStatus.err:
#        return HttpResponse('We had some errors <pre>' + html + '</pre>')
#     return response
from orphanage.utils import get_scholar_year


class StudentCardPDF(PDFTemplateView):

    cmd_options = {
        'page-width': '140',
        'page-height': '80',
        'orientation': 'portrait',
        'margin-top': 0,
        'margin-bottom': 0,
        'margin-left': 0,
        'margin-right': 0,
    }

    filename = None

    template_name = 'orphanage/pdf/student_card.html'

    context = {}

    def get(self, request, *args, **kwargs):

        if 'student_id' in kwargs:
            students = Student.objects.filter(pk=kwargs['student_id'])
            if not students:
                raise Http404()
            student_title = 'التلميذ' if students[0].sex == 'm' else 'التلميذة'
            messages.success(request, 'لقد تمت طباعة بطاقة ' + student_title + ' بنجاح.')
        else:
            if 'students_ids' in kwargs:
                students = Student.objects.filter(id__in=kwargs['students_ids'])
            else:
                students = Student.objects.all()
            messages.success(request, 'تمت طباعة بطاقات الأطفال بنجاح.')

        self.context['students'] = students
        self.context['scholar_year'] = get_scholar_year(switch_month=6)

        if request.GET.get('as', '') == 'html':
            return TemplateResponse(
                request=request, template=self.template_name, context=self.context,
            )

        return PDFTemplateResponse(
            request=request, template=self.template_name, filename=self.filename, context=self.context,
            show_content_in_browser=False, cmd_options=self.cmd_options,
        )

orphanage/templates/orphanage/children_list.html
{% extends 'orphanage/base.html' %}
{% load staticfiles %}

{% block stylesheets %}
    <!-- Data Table CSS -->
    <link href="{% static 'orphanage/vendors/datatables.net-dt/css/jquery.dataTables.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'orphanage/vendors/datatables.net-responsive-dt/css/responsive.dataTables.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock stylesheets %}

{% block main %}
    <div class="page-content">
        <div class="hk-pg-header pt-4 mb-0">
            <h4 class="hk-pg-title rtl font-weight-bold w-100 justify-content-end pr-4 pt-2 pb-0">
                لائحة الأطفال
            </h4>
        </div>

        <div class="hk-sec-wrapper m-3">
                <div class="row">
                    <div class="col-sm-12 col-md-6">
    {#                    <div class="dataTables_length" id="datable_1_length">#}
    {#                        <label class="w-100 d-flex justify-content-start align-items-center">#}
    {#                            <select name="datable_1_length"#}
    {#                                    aria-controls="datable_1"#}
    {#                                    class="custom-select custom-select-sm form-control form-control-sm w-25 mr-2">#}
    {#                                <option value="10">10</option>#}
    {#                                <option value="25">25</option>#}
    {#                                <option value="50">50</option>#}
    {#                                <option value="100">100</option>#}
    {#                            </select> عدد الأسطر في الصفحة#}
    {#                        </label>#}
    {#                    </div>#}
    {#                    <div class="actions">#}
    {#                        <a class="btn-sm btn-primary font-weight-bold" href="{% url 'orphanage:print_cards' %}">طباعة البطاقات</a>#}
    {#                    </div>#}
                        <div class="btn-toolbar d-inline-block mb-25 mr-10" role="toolbar" aria-label="Toolbar with button groups">
                            <div class="btn-group mr-2" role="group" aria-label="First group">
{#                                <a  class="btn btn-outline-light" onclick="print()" title="طباعة البطاقات"><i class="icon-printer"></i></a>#}
                                <a  class="btn btn-outline-light" href="{% url 'orphanage:print_cards' %}" target="_blank" title="طباعة البطاقات">
                                    <i class="icon-printer"></i>
                                </a>
    {#                            <button type="button" class="btn btn-outline-light"><i class="icon-list"></i></button>#}
    {#                            <button type="button" class="btn btn-outline-light"><i class="icon-menu"></i></button>#}
    {#                            <button type="button" class="btn btn-outline-light"><i class="icon-login"></i></button>#}
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        <div id="datable_1_filter" class="dataTables_filter d-flex justify-content-end">
                            <form action="">
                                <label>
                                    <input type="search" onkeydown="search()" name="name" class="form-control form-control-sm" placeholder="بحث" aria-controls="datable_1">
                                    <input type="submit" class="d-none">
                                </label>
                            </form>
                        </div>
                    </div>
                </div>

            <form action="" method="POST" id="children_form">
                {% csrf_token %}
                <table class="table table-hover table-striped table-sm table-bordered children-table">
                    <thead class="thead-active">
                    <tr class="rtl">
                        <th scope="col">الهواية</th>
                        <th scope="col">الدوار</th>
                        <th scope="col">رقم الهاتف</th>
                        <th scope="col">تاريخ الإزدياد</th>
                        <th scope="col">المستوى الدراسي</th>
                        <th scope="col">اللقب</th>
                        <th scope="col">الإسم</th>
                        <th scope="col">الصورة</th>
                        <th scope="col">
                            <input type="checkbox" id="select_all">
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for child in items %}
                        <tr class="rtl">
                            <td onclick="location.href='{% url 'orphanage:child_details' child.id %}'">{{ child.hobby|default_if_none:'' }}</td>
                            <td onclick="location.href='{% url 'orphanage:child_details' child.id %}'">{{ child.village|default_if_none:'' }}</td>
                            <td onclick="location.href='{% url 'orphanage:child_details' child.id %}'">{{ child.phone_number|default_if_none:'' }}</td>
                            <td onclick="location.href='{% url 'orphanage:child_details' child.id %}'">{{ child.birthday|date:'Y/m/d'|default_if_none:'' }}</td>
                            <td onclick="location.href='{% url 'orphanage:child_details' child.id %}'">{{ child.grade|default_if_none:'' }}</td>
                            <td onclick="location.href='{% url 'orphanage:child_details' child.id %}'">{{ child.last_name }}</td>
                            <td onclick="location.href='{% url 'orphanage:child_details' child.id %}'">{{ child.first_name }}</td>
                            <th onclick="location.href='{% url 'orphanage:child_details' child.id %}'"><img src="{% if child.picture %}{{ child.picture.url }}{% else %}/static/orphanage/img/default/{% if child.sex == 'm' %}boy{% else %}girl{% endif %}_avatar.png{% endif %}"></th>
                            <td>
                                <input type="checkbox" class="child_select" name="children" value="{{ child.id }}">
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>
            {% include 'orphanage/includes/pagination.html' %}
        </div>

    </div>
    <!-- /Main Content -->
{% endblock main %}

{% block js %}
    <script>
        // select all checkboxes
        $('#select_all').click(function() {
            let check_boxes = $('.child_select');
            if ($(this).is(':checked')) {
                check_boxes.attr('checked', true);
            } else {
                check_boxes.attr('checked', false);
            }
        });
    </script>

    <script>
        // print children's cards
        function print() {
            let form = $('#children_form');
            form.append('<input type="hidden" name="action" value="print">');
            form.submit();
        }
    </script>
{% endblock js %}

orphanage/templates/orphanage/home.html
{% extends 'orphanage/base.html' %}
{% load staticfiles %}

{% block extra_css %}
    <style>
        .main-stats .card {
            transition: .3s;
            box-shadow: 0 0 0 transparent;
        }
        .main-stats .card:hover {
            box-shadow: 0 0 20px rgba(0, 0, 0, .2);
        }
    </style>
{% endblock %}

{% block content_header %}
<!-- <div class="content-header-left col-md-6 col-12 mb-1">
  <h3 class="content-header-title font-weight-bold">{{ page_title_ar }}</h3>
</div> -->
{% endblock content_header %}

{% block content_body %}
<div class="row main-stats">
    <div class="col-xl-3 col-lg-6 col-12">
        <div class="card">
            <div class="card-content">
                <a href="{% url 'orphanage:children' %}" class="text-white">
                    <div class="media align-items-stretch">
                        <div class="p-2 text-center bg-primary bg-darken-2">
                            <i class="ft-users font-large-2 white"></i>
                        </div>
                        <div class="p-2 bg-gradient-x-primary white media-body">
                            <h2>الأطفال</h2>
                            <h3 class="text-bold-400 mb-0">{{ children_count }}</h3>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-lg-6 col-12">
        <div class="card">
            <div class="card-content">
                <a href="{% url 'orphanage:grades' %}" class="text-white">
                    <div class="media align-items-stretch">
                        <div class="p-2 text-center bg-danger bg-darken-2">
                            <i class="ft-layers font-large-2 white"></i>
                        </div>
                        <div class="p-2 bg-gradient-x-danger white media-body">
                            <h2>المستويات</h2>
                            <h3 class="text-bold-400 mb-0">{{ grades_count }}</h3>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-lg-6 col-12">
        <div class="card">
            <div class="card-content">
                <a href="#{#% url 'orphanage:subjects' %#}" class="text-white">
                    <div class="media align-items-stretch">
                        <div class="p-2 text-center bg-warning bg-darken-2">
                            <i class="ft-book font-large-2 white"></i>
                        </div>
                        <div class="p-2 bg-gradient-x-warning white media-body">
                            <h2>المواد</h2>
                            <h3 class="text-bold-400 mb-0">{{ subjects_count }}</h3>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-lg-6 col-12">
        <div class="card">
            <div class="card-content">
                <a href="#{#% url 'orphanage:guardians' %#}" class="text-white">
                    <div class="media align-items-stretch">
                        <div class="p-2 text-center bg-success bg-darken-2">
                            <i class="ft-shield font-large-2 white"></i>
                        </div>
                        <div class="p-2 bg-gradient-x-success white media-body">
                            <h2>الكفلاء</h2>
                            <h3 class="text-bold-400 mb-0">{{ guardians_count }}</h3>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content_body %}

{% block js %}
{% endblock js %}

orphanage/templates/orphanage/profile.html
{% extends 'orphanage/base.html' %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block  content_body %}
    <h1>Profile</h1>
{% endblock content_body %}

{% block js %}
{% endblock js %}