kafili/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from kafili import settings
from orphanage.views import home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^orphanage/', include('orphanage.urls', namespace="orphanage")),
    url('^$', home),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'orphanage.views.handler_404'
handler500 = 'orphanage.views.handler_500'
handler403 = 'orphanage.views.handler_403'

orphanage/urls.py
from django.conf.urls import url
from wkhtmltopdf.views import PDFTemplateView

from orphanage.views import *

app_name = 'orphanage'

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', connexion, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^request_registration/$', request_registration, name='request_registration'),
    url(r'^profile/$', profile, name='profile'),

    # Children
    url(r'^children/$', children, name='children'),
    url(r'^children/insert/$', child_insert, name='child_insert'),
    url(r'^children/print_cards/$', StudentCardPDF.as_view(), name='print_cards'),
    url(r'^children/(?P<child_id>[0-9]+)/$', child_details, name='child_details'),
    url(r'^children/(?P<child_id>[0-9]+)/print_card/$', StudentCardPDF.as_view(), name='print_card'),
    url(r'^children/(?P<child_id>[0-9]+)/update/$', child_update, name='child_update'),
    
    # Guardians
    # url(r'^guardians/$', guardians, name='guardians'),
    # url(r'^guardians/(?P<guardian_id>[0-9]+)/$', guardian_details, name='guardian_details'),
    # url(r'^guardians/(?P<guardian_id>[0-9]+)/update/$', guardian_update, name='guardian_update'),
    # url(r'^guardians/insert/$', guardian_insert, name='guardian_insert'),
    
    # Years
    url(r'^year/$', year_details, name='year_details'),
    url(r'^year/insert/$', year_insert, name='year_insert'),
    url(r'^year/switch/(?P<year>[0-9]{4})/$', year_switch, name='year_switch'),
    
    # Grades
    url(r'^grades/$', grades, name='grades'),
    url(r'^grades/(?P<grade_id>[0-9]+)/$', grade_details, name='grade_details'),
    url(r'^grades/(?P<grade_id>[0-9]+)/update/$', grade_update, name='grade_update'),
    url(r'^grades/insert/$', grade_insert, name='grade_insert'),

    # Students
    url(r'^grades/(?P<grade_id>[0-9]+)/students/$', students, name='students'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/insert/$', student_insert, name='student_insert'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/print_cards/$', StudentCardPDF.as_view(), name='print_cards'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/$', student_details, name='student_details'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/print_card/$', StudentCardPDF.as_view(), name='print_card'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/update/$', student_update, name='student_update'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/marks/$', student_marks, name='student_marks'),

    # Website
    # url(r'^grades/(?P<grade_id>[0-9]+)/subjects/insert/$', subject_insert, name='subject_insert'),

]

orphanage/models.py
import os

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db.utils import IntegrityError
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User

from orphanage.services import calculate_decision
from orphanage import settings as orphanage_settings


class Child(models.Model):

    class Meta:
        verbose_name = 'طفل'
        verbose_name_plural = 'أطفال'
        ordering = ('first_name', 'last_name')

    # TODO: add this field in insert and update templates and forms
    subscription_id = models.PositiveIntegerField('رقم الإنخراط', unique=True, null=True, blank=True)
    first_name = models.CharField('الإسم', max_length=255)
    last_name = models.CharField('اللقب', max_length=255)
    full_name = models.CharField('الإسم الكامل', max_length=255, null=True, blank=True)
    picture = models.ImageField('الصورة', upload_to='images/students', null=True, blank=True)
    sex = models.CharField('الجنس', max_length=1, choices=orphanage_settings.SEX_CHOICES, null=True, blank=True)
    grade = models.CharField('المستوى الدراسي', max_length=10, null=True, blank=True)
    birthday = models.DateField('تاريخ الإزدياد', null=True, blank=True)
    phone_number = models.CharField('رقم الهاتف', max_length=25, null=True, blank=True)
    village = models.CharField('الدوار', max_length=155, null=True, blank=True)
    weight = models.PositiveSmallIntegerField('الوزن', null=True, blank=True)
    height = models.PositiveSmallIntegerField('القامة', null=True, blank=True)
    bed_position = models.CharField('تموضع السرير', max_length=15, null=True, blank=True)
    shoo_size = models.CharField('مقاس الحذاء', max_length=8, null=True, blank=True)
    vision = models.CharField('الرؤية', max_length=55, null=True, blank=True)
    orphan_side = models.CharField('اليتم', choices=orphanage_settings.ORPHAN_CHOICES, max_length=10, null=True, blank=True)
    chronic_disease = models.CharField('مرض مزمن', max_length=55, null=True, blank=True)
    hobby = models.CharField('الهواية', max_length=25, null=True, blank=True)
    status = models.CharField('الحالة', max_length=10, choices=orphanage_settings.STATUS_CHOICES, default="", blank=True)

    # Functions
    def __str__(self):
        return self.full_name if self.full_name else ''

    def get_short_address(self):
        return 'دوار ' + self.village + '، جماعة زرقطن' if self.village else ''

    def get_address(self):
        return 'دوار ' + self.village + '، جماعة زرقطن، قيادة التوامة، عمالة تاحناوت' if self.village else ''

    def update_full_name(self):
        self.full_name = self.first_name + ' ' + self.last_name
        self.save(update_fields=['full_name', ])

    def get_students(self):
        return self.student_set.all()

    def get_student(self, year=None):
        if not year:
            year = Year.objects.first()
        students = self.get_students()
        if students:
            return students.get(grade__year=year)
        else:
            return None

    def create_child(self):
        self.save()

    def update_child(self):
        self.save()

    def delete_child(self):
        self.save()

    def delete(self, *args, **kwargs):
        super(Student, self).delete(*args, **kwargs)

    @classmethod
    def delete_children(cls, children):
        success, message = True, "لقد تمت العملية بنجاح."
        for child in children:
            success, msg = child.delete_child()
            if not success:
                message = msg
                break
        return success, message

    @classmethod
    def list(cls, **kwargs):

        filters = Q()
        if 's_query' in kwargs:
            name = kwargs['s_query'][0]
            filters = Q(first_name__icontains=name) | Q(last_name__icontains=name) | Q(full_name__icontains=name)
        if 'name' in kwargs:
            name = kwargs['name'][0]
            filters = Q(first_name__icontains=name) | Q(last_name__icontains=name) | Q(full_name__icontains=name)
        if 'ids' in kwargs:
            ids = kwargs['ids']
            filters &= Q(id__in=ids)

        if 'subscription_id' in kwargs and kwargs['subscription_id'][0]:
            subscription_id = kwargs['subscription_id'][0]
            filters = Q(subscription_id=subscription_id)
        if 'sex' in kwargs and kwargs['sex'][0]:
            sex = kwargs['sex'][0]
            filters = Q(sex=sex)
        if 'village' in kwargs and kwargs['village'][0]:
            village = kwargs['village'][0]
            filters = Q(village__icontains=village)
        if 'shoo_size' in kwargs and kwargs['shoo_size'][0]:
            shoo_size = kwargs['shoo_size'][0]
            filters = Q(shoo_size__icontains=shoo_size)
        if 'vision' in kwargs and kwargs['vision'][0]:
            vision = kwargs['vision'][0]
            filters = Q(vision__icontains=vision)
        if 'orphan_side' in kwargs and kwargs['orphan_side'][0]:
            orphan_side = kwargs['orphan_side'][0]
            filters = Q(orphan_side=orphan_side)
        if 'chronic_disease' in kwargs and kwargs['chronic_disease'][0]:
            chronic_disease = kwargs['chronic_disease'][0]
            filters = Q(chronic_disease__icontains=chronic_disease)
        if 'hobby' in kwargs and kwargs['hobby'][0]:
            hobby = kwargs['hobby'][0]
            filters = Q(hobby__icontains=hobby)
        if 'status' in kwargs and kwargs['status'][0]:
            status = kwargs['status'][0]
            filters = Q(status=status)

        return cls.objects.filter(filters)

    @classmethod
    def import_photos(cls):
        students = cls.objects.all()

        basedir = settings.BASE_DIR
        path = basedir + f'{settings.MEDIA_URL}images/children'
        if not os.path.exists(path):
            os.mkdir(path)
        not_imported = []
        success_import_count = 0

        for img in os.listdir(path):
            try:
                value = img.split('.')[0]

                if not value.isdigit():
                    continue
                student = students.get(id=value)
                if not student.picture or 1:
                    img_path = f'images/children/{img}'
                    student.picture = img_path
                    student.save(update_fields=['picture', ])
                    print(student)
                    success_import_count += 1

            except ObjectDoesNotExist:
                not_imported.append(img)

        err_message = ''
        if not_imported:
            non_importees = ''
            for img in not_imported:
                non_importees += img + '; '
            err_message = f'({len(not_imported)}/{len(os.listdir(path))}) Images were not imported: {non_importees}'

        message = f"لقد تم إستيراد {success_import_count} صورة."
        return True, message, err_message


class Student(models.Model):

    class Meta:
        verbose_name = 'تلميذ'
        verbose_name_plural = 'تلاميذ'
        ordering = ('child', )

    child = models.ForeignKey(Child, verbose_name="الطفل", on_delete=models.PROTECT)
    grade = models.ForeignKey('Grade', verbose_name="المستوى الدراسي", on_delete=models.PROTECT)
    s1_mark = models.DecimalField('نقطة الدورة الأولى', max_digits=4, decimal_places=2, null=True, blank=True)
    s1_decision = models.CharField('ميزة الدورة الأولى', max_length=2, choices=orphanage_settings.STUDENT_DECISION_CHOICES, default="", blank=True)
    s2_mark = models.DecimalField('نقطة الدورة الثانية', max_digits=4, decimal_places=2, null=True, blank=True)
    s2_decision = models.CharField('ميزة الدورة الثانية', max_length=2, choices=orphanage_settings.STUDENT_DECISION_CHOICES, default="", blank=True)
    year_mark = models.DecimalField('معدل السنة', max_digits=4, decimal_places=2, null=True, blank=True)
    year_decision = models.CharField('ميزة السنة', max_length=2, choices=orphanage_settings.STUDENT_DECISION_CHOICES, default="", blank=True)
    status = models.CharField('الحالة', max_length=10, choices=orphanage_settings.STATUS_CHOICES, default='passed', blank=True)

    # Functions
    def __str__(self):
        return f"{self.child} - {self.grade}"

    def save(self, grade=None, *args, **kwargs):
        if not self.id:
            self.grade = grade
        
        if 's1_mark' in kwargs['update_fields'] or 's2_mark' in kwargs['update_fields'] or 'year_mark' in kwargs['update_fields']:
            self.update_decisions()
        super(Student, self).save(*args, **kwargs)
    
    def update_decisions(self):
        self.s1_decision = calculate_decision(self.s1_mark)
        self.s2_decision = calculate_decision(self.s2_mark)
        self.year_decision = calculate_decision(self.year_mark)
        super(Student, self).save()

    def delete(self, *args, **kwargs):
        super(Student, self).delete(*args, **kwargs)

    @classmethod
    def delete_students(cls, students):
        res, message = True, "لقد تمت العملية بنجاح."
        for student in students:
            student.delete()
        return res, message

    @classmethod
    def list(cls, grade, **kwargs):

        filters = Q(grade=grade)
        if 's_query' in kwargs:
            name = kwargs['s_query'][0]
            filters &= Q(child__first_name__icontains=name) | Q(child__last_name__icontains=name) | Q(child__full_name__icontains=name)
        if 'name' in kwargs:
            name = kwargs['name'][0]
            filters &= Q(child__first_name__icontains=name) | Q(child__last_name__icontains=name) | Q(child__full_name__icontains=name)
        if 'ids' in kwargs:
            ids = kwargs['ids']
            filters &= Q(id__in=ids)

        if 'subscription_id' in kwargs and kwargs['subscription_id'][0]:
            subscription_id = kwargs['subscription_id'][0]
            filters = Q(child__subscription_id=subscription_id)
        if 'status' in kwargs and kwargs['status'][0]:
            status = kwargs['status'][0]
            filters = Q(status=status)

orphanage/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import logout as django_logout

from orphanage.forms import ConnectionForm, ChildForm
from orphanage.models import Child


def connexion(request):
    user = request.user if request.user.is_authenticated else None
    if request.method == 'POST':
        form = ConnectionForm(request.POST)
        if not user:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
        if user and user.is_active:
            login(request, user)
            url = request.GET.get('next') if 'next' in request.GET else reverse('orphanage:home')
            return redirect(url)
    else:
        form = ConnectionForm()

    return render(request, 'orphanage/login.html', {
        'form': form,
    })


def logout(request):
    django_logout(request)
    return redirect(reverse('orphanage:login'))


@login_required
def profile(request):

    return render(request, 'orphanage/profile.html')


@login_required
def children_list(request):
    children = Child.list()

    number_per_page = 20
    next_page = None
    previous_page = None

    paginator = Paginator(children, number_per_page)
    if request.GET.get('page'):
        page = request.GET.get('page')
    else:
        page = 1
    try:
        orphans_page = paginator.page(page)
    except PageNotAnInteger:
        orphans_page = paginator.page(1)
    except EmptyPage:
        orphans_page = paginator.page(paginator.num_pages)

    if orphans_page.has_next():
        next_page = orphans_page.next_page_number()
    if orphans_page.has_previous():
        previous_page = orphans_page.previous_page_number()

    context = {
        'items': orphans_page,
        'number_per_page': number_per_page,
        'page': page,
        'number_of_pages': paginator.num_pages,
        'range': paginator.page_range,
        'next_page': next_page,
        'previous_page': previous_page,
    }

    return render(request, 'orphanage/children_list.html', context)


@login_required
def child_details(request, id):
    child = Child.objects.get(pk=id)

    context = {
        'child': child,
    }

    return render(request, 'orphanage/child_details.html', context)


@login_required
def child_insert(request):
    
    form = ChildForm()

    context = {
        'form': form
    }

    return render(request, 'orphanage/child_update.html', context)


@login_required
def child_update(request, id):

    try:
        child = Child.objects.get(id=id)
    except ObjectDoesNotExist:
        return Http404()

    if request.method == 'POST':
        form = ChildForm(data=request.POST, files=request.FILES, instance=child)
        if form.is_valid():
            form.instance.birthday = form.cleaned_data['birthday']
            form.instance.save()
            return redirect(reverse('orphanage:child_details', args=[child.id]))
    else:
        form = ChildForm(instance=child, initial={'birthday': child.birthday})

    context = {
        'form': form,
    }

    return render(request, 'orphanage/child_update.html', context)

orphanage/views/error_handlers.py
from django.shortcuts import render_to_response


def handler_404(request, exception):
    template_name = 'orphanage/errors/404.html'
    response = render_to_response(template_name)
    response.status_code = 404
    return response


def handler_500(request):
    template_name = 'orphanage/errors/500.html'
    response = render_to_response(template_name)
    response.status_code = 500
    return response


def handler_403(request, exception):  # permission denied
    template_name = 'orphanage/errors/403.html'
    response = render_to_response(template_name)
    response.status_code = 403
    return response

orphanage/templates/orphanage/student/student_marks.html
{% extends 'orphanage/base.html' %}

{% block  content_body %}
    <h1>CHILD MARKS</h1>
{% endblock  content_body %}

orphanage/templates/orphanage/student/student_update.html
{% extends 'orphanage/base.html' %}
{% load staticfiles %}

{% block extra_css %}
    <style>
        img.image {
            width: 100%;
        }
        label.custom-file-label::after {
            content: 'تصفح' !important;
        }
    </style>

    {% include 'orphanage/imports/css/forms.html' %}

{% endblock extra_css %}

{% block header_actions %}
    <div class="btn-group float-md-right" role="group" aria-label="Button group with nested dropdown">
        <a class="btn btn-outline-primary" href="{% if form.instance.id %}{%  url 'orphanage:student_details' grade.id form.instance.id %}{% else %}{%  url 'orphanage:students' grade.id  %}{% endif %}">
            <i class="ft-x"></i> إلغاء
        </a>
    </div>
{% endblock header_actions %}

{% block  content_body %}
    <div class="page-content">

        <div class="container mt-3">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-9 col-sm-12">
                        <div class="row">
                            <div class="col-md-6 col-sm-12 form-group{% if form.child.errors %} error{% endif %}">
                                <label class="font-weight-bold" for="id_child">{{ form.child.label }}</label>
                                {{ form.child }}
                                {% if form.child.errors %}
                                    <div class="help-block"><ul class="alert">
                                        {% for error in form.child.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul></div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 col-sm-12 form-group{% if form.status.errors %} error{% endif %}">
                                <label class="font-weight-bold" for="id_status">{{ form.status.label }}</label>
                                {{ form.status }}
                                {% if form.status.errors %}
                                    <div class="help-block"><ul class="alert">
                                        {% for error in form.status.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul></div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 col-sm-12 form-group{% if form.s1_mark.errors %} error{% endif %}">
                                <label class="font-weight-bold" for="id_s1_mark">{{ form.s1_mark.label }}</label>
                                {{ form.s1_mark }}
                                {% if form.s1_mark.errors %}
                                    <div class="help-block"><ul class="alert">
                                        {% for error in form.s1_mark.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul></div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 col-sm-12 form-group{% if form.s2_mark.errors %} error{% endif %}">
                                <label class="font-weight-bold" for="id_s2_mark">{{ form.s2_mark.label }}</label>
                                {{ form.s2_mark }}
                                {% if form.s2_mark.errors %}
                                    <div class="help-block"><ul class="alert">
                                        {% for error in form.s2_mark.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul></div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 col-sm-12 form-group{% if form.year_mark.errors %} error{% endif %}">
                                <label class="font-weight-bold" for="id_year_mark">{{ form.year_mark.label }}</label>
                                {{ form.year_mark }}
                                {% if form.year_mark.errors %}
                                    <div class="help-block"><ul class="alert">
                                        {% for error in form.year_mark.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul></div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <a class="btn btn-secondary font-weight-bold" href="{% if form.instance.id %}{% url 'orphanage:student_details' grade.id form.instance.id %}{% else %}{% url 'orphanage:students' grade.id %}{% endif %}">
                            إلغاء
                        </a>
                        <button class="btn btn-primary font-weight-bold" type="submit" name="action" value="save">
                            {% if form.instance.id %}تحديث{% else %}إضافة{% endif %}
                            </button>
                    </div>
                </div>
            </form>
        </div>

    </div>
{% endblock content_body %}

{% block extra_js %}

    {% include 'orphanage/imports/js/forms.html' %}

    <script>
        $('.datetimepicker').datetimepicker({
            viewMode: 'years',
            locale: 'fr',
		    format: 'DD/MM/YYYY'
        });
    </script>

{% endblock extra_js %}