kafili/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from kafili import settings
from orphanage.views import home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^orphanage/', include('orphanage.urls', namespace="orphanage")),
    url('^$', home),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'orphanage.views.handler_404'
handler500 = 'orphanage.views.handler_500'
handler403 = 'orphanage.views.handler_403'

orphanage/urls.py
from django.conf.urls import url
from wkhtmltopdf.views import PDFTemplateView

from orphanage.views import *

app_name = 'orphanage'

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', connexion, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^request_registration/$', request_registration, name='request_registration'),
    url(r'^profile/$', profile, name='profile'),

    # Children
    url(r'^children/$', children, name='children'),
    url(r'^children/insert/$', child_insert, name='child_insert'),
    url(r'^children/print_cards/$', StudentCardPDF.as_view(), name='print_cards'),
    url(r'^children/(?P<child_id>[0-9]+)/$', child_details, name='child_details'),
    url(r'^children/(?P<child_id>[0-9]+)/print_card/$', StudentCardPDF.as_view(), name='print_card'),
    url(r'^children/(?P<child_id>[0-9]+)/update/$', child_update, name='child_update'),
    
    # Guardians
    # url(r'^guardians/$', guardians, name='guardians'),
    # url(r'^guardians/(?P<guardian_id>[0-9]+)/$', guardian_details, name='guardian_details'),
    # url(r'^guardians/(?P<guardian_id>[0-9]+)/update/$', guardian_update, name='guardian_update'),
    # url(r'^guardians/insert/$', guardian_insert, name='guardian_insert'),
    
    # Years
    url(r'^year/$', year_details, name='year_details'),
    url(r'^year/insert/$', year_insert, name='year_insert'),
    url(r'^year/switch/(?P<year>[0-9]{4})/$', year_switch, name='year_switch'),
    
    # Grades
    url(r'^grades/$', grades, name='grades'),
    url(r'^grades/(?P<grade_id>[0-9]+)/$', grade_details, name='grade_details'),
    url(r'^grades/(?P<grade_id>[0-9]+)/update/$', grade_update, name='grade_update'),
    url(r'^grades/insert/$', grade_insert, name='grade_insert'),

    # Students
    url(r'^grades/(?P<grade_id>[0-9]+)/students/$', students, name='students'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/insert/$', student_insert, name='student_insert'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/print_cards/$', StudentCardPDF.as_view(), name='print_cards'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/$', student_details, name='student_details'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/print_card/$', StudentCardPDF.as_view(), name='print_card'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/update/$', student_update, name='student_update'),
    url(r'^grades/(?P<grade_id>[0-9]+)/students/(?P<student_id>[0-9]+)/marks/$', student_marks, name='student_marks'),

    # Website
    # url(r'^grades/(?P<grade_id>[0-9]+)/subjects/insert/$', subject_insert, name='subject_insert'),

]

orphanage/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import logout as django_logout

from orphanage.forms import ConnectionForm, ChildForm
from orphanage.models import Child


def connexion(request):
    user = request.user if request.user.is_authenticated else None
    if request.method == 'POST':
        form = ConnectionForm(request.POST)
        if not user:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
        if user and user.is_active:
            login(request, user)
            url = request.GET.get('next') if 'next' in request.GET else reverse('orphanage:home')
            return redirect(url)
    else:
        form = ConnectionForm()

    return render(request, 'orphanage/login.html', {
        'form': form,
    })


def logout(request):
    django_logout(request)
    return redirect(reverse('orphanage:login'))


@login_required
def profile(request):

    return render(request, 'orphanage/profile.html')


@login_required
def children_list(request):
    children = Child.list()

    number_per_page = 20
    next_page = None
    previous_page = None

    paginator = Paginator(children, number_per_page)
    if request.GET.get('page'):
        page = request.GET.get('page')
    else:
        page = 1
    try:
        orphans_page = paginator.page(page)
    except PageNotAnInteger:
        orphans_page = paginator.page(1)
    except EmptyPage:
        orphans_page = paginator.page(paginator.num_pages)

    if orphans_page.has_next():
        next_page = orphans_page.next_page_number()
    if orphans_page.has_previous():
        previous_page = orphans_page.previous_page_number()

    context = {
        'items': orphans_page,
        'number_per_page': number_per_page,
        'page': page,
        'number_of_pages': paginator.num_pages,
        'range': paginator.page_range,
        'next_page': next_page,
        'previous_page': previous_page,
    }

    return render(request, 'orphanage/children_list.html', context)


@login_required
def child_details(request, id):
    child = Child.objects.get(pk=id)

    context = {
        'child': child,
    }

    return render(request, 'orphanage/child_details.html', context)


@login_required
def child_insert(request):
    
    form = ChildForm()

    context = {
        'form': form
    }

    return render(request, 'orphanage/child_update.html', context)


@login_required
def child_update(request, id):

    try:
        child = Child.objects.get(id=id)
    except ObjectDoesNotExist:
        return Http404()

    if request.method == 'POST':
        form = ChildForm(data=request.POST, files=request.FILES, instance=child)
        if form.is_valid():
            form.instance.birthday = form.cleaned_data['birthday']
            form.instance.save()
            return redirect(reverse('orphanage:child_details', args=[child.id]))
    else:
        form = ChildForm(instance=child, initial={'birthday': child.birthday})

    context = {
        'form': form,
    }

    return render(request, 'orphanage/child_update.html', context)

orphanage/views/child_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from orphanage import settings as orphanage_settings
from orphanage.decorators import valid_session
from orphanage.forms import ChildForm, ChildFilterForm
from orphanage.models import Child


@login_required
@valid_session
def children(request):

    qset = Child.list(**request.GET)

    table_size = orphanage_settings.TABLE_SIZE
    if 'tablesize' in request.GET:
        try:
            tmp_table_size = int(request.GET['tablesize'])
            if tmp_table_size > 0:
                table_size = tmp_table_size
        except ValueError:
            pass
    next_page = None
    previous_page = None

    paginator = Paginator(qset, table_size)
    if request.GET.get('page'):
        page = request.GET.get('page')
    else:
        page = 1
    try:
        orphans_page = paginator.page(page)
    except PageNotAnInteger:
        orphans_page = paginator.page(1)
    except EmptyPage:
        orphans_page = paginator.page(paginator.num_pages)

    if orphans_page.has_next():
        next_page = orphans_page.next_page_number()
    if orphans_page.has_previous():
        previous_page = orphans_page.previous_page_number()

    initial_dict = {}
    for key in request.GET.keys():
        if request.GET[key]:
            initial_dict[key] = request.GET[key]

    # POST METHOD
    if request.method == 'POST':
        if request.POST.get('action', '') == 'delete_multiple':
            children = Child.objects.filter(pk__in=request.POST.getlist('objects_ids', ''))
            res, message = Child.delete_children(children)
            if res:
                messages.success(request, message)
            else:
                messages.error(request, message)
            return redirect(reverse('orphanage:children'))
        elif request.POST.get('action', '') == 'import_pictures':
            res, message, err_msg = Child.import_photos()
            messages.success(request, message)
            if err_msg:
                messages.warning(request, err_msg)
            return redirect(reverse('orphanage:children'))

    context = {
        'items': orphans_page,
        'table_size': table_size,
        'page': page,
        'filter_form': ChildFilterForm(initial=initial_dict),
        'number_of_pages': paginator.num_pages,
        'range': paginator.page_range,
        'next_page': next_page,
        'previous_page': previous_page,
        'page_title': 'Children',
        'page_title_ar': 'لائحة الأطفال'
    }

    return render(request, 'orphanage/child/children_list.html', context)


@login_required
@valid_session
def child_insert(request):
    
    if request.method == 'POST':
        form = ChildForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.instance.birthday = form.cleaned_data['birthday']
            form.instance.save()
            child_title = 'الطفل' if form.instance.sex == 'm' else 'الطفلة'
            messages.success(request, 'تمت إضافة ' + child_title + ' بنجاح.')
            return redirect(reverse('orphanage:child_details', args=[form.instance.id]))
        messages.error(request, 'المرجو مراجعة بيانات الطفل(ة)')
    else:
        form = ChildForm()

    context = {
        'form': form,
        'page_title': 'Child insert',
        'page_title_ar': f'إضافة تلميذ(ة)'
    }

    return render(request, 'orphanage/child/child_update.html', context)


@login_required
@valid_session
def child_details(request, child_id):
    
    child = get_object_or_404(Child, id=child_id)
    child_title = 'الطفل' if child.sex == 'm' else 'الطفلة'

    if request.method == 'POST':
        if request.POST['action'] == 'delete':
            child.delete()
            return redirect(reverse('orphanage:children'))

    context = {
        'child': child,
        'page_title': 'Child details',
        'page_title_ar': f'بيانات {child_title} {child}'
    }

    return render(request, 'orphanage/child/child_details.html', context)


@login_required
@valid_session
def child_update(request, child_id):

    child = get_object_or_404(Child, id=child_id)

    if request.method == 'POST':
        form = ChildForm(data=request.POST, files=request.FILES, instance=child)
        if form.is_valid():
            form.instance.birthday = form.cleaned_data['birthday']
            form.instance.save()
            child_title = 'الطفل' if child.child.sex == 'm' else 'الطفلة'
            messages.success(request, 'تمت عملية تحديث بيانات ' + child_title + ' بنجاح.')
            return redirect(reverse('orphanage:child_details', args=[child.id]))
        messages.error(request, f'المرجو مراجعة بيانات الطفل(ة) {form.errors}')
    else:
        form = ChildForm(instance=child, initial={'birthday': child.birthday})

    context = {
        'form': form,
        'page_title': 'Child update',
        'page_title_ar': f'تحديث بيانات الأطفال {child}'
    }

    return render(request, 'orphanage/child/child_update.html', context)


@login_required
@valid_session
def child_marks(request, child_id):
    
    child = get_object_or_404(Child, id=child_id)

    if request.method == 'POST':
        if request.POST['action'] == 'delete':
            child.delete()
            return redirect(reverse('orphanage:children'))

    context = {
        'child': child,
        'page_title': 'Child marks',
        'page_title_ar': f'علامات الأطفال {child}'
    }

    return render(request, 'orphanage/child/child_marks.html', context)

orphanage/views/error_handlers.py
from django.shortcuts import render_to_response


def handler_404(request, exception):
    template_name = 'orphanage/errors/404.html'
    response = render_to_response(template_name)
    response.status_code = 404
    return response


def handler_500(request):
    template_name = 'orphanage/errors/500.html'
    response = render_to_response(template_name)
    response.status_code = 500
    return response


def handler_403(request, exception):  # permission denied
    template_name = 'orphanage/errors/403.html'
    response = render_to_response(template_name)
    response.status_code = 403
    return response

orphanage/views/printing.py
from django.contrib import messages
from django.http import Http404
from django.template.response import TemplateResponse

from wkhtmltopdf.views import PDFTemplateView, PDFTemplateResponse

from orphanage.models import Student

# import os
# from django.conf import settings
# from django.http import HttpResponse
# from django.template import Context
# from django.template.loader import get_template
# from xhtml2pdf import pisa
#
#
# def link_callback(uri, rel):
#     """
#     Convert HTML URIs to absolute system paths so xhtml2pdf can access those
#     resources
#     """
#     # use short variable names
#     sUrl = settings.STATIC_URL      # Typically /static/
#     sRoot = settings.STATIC_ROOT    # Typically /home/userX/project_static/
#     mUrl = settings.MEDIA_URL       # Typically /static/media/
#     mRoot = settings.MEDIA_ROOT     # Typically /home/userX/project_static/media/
#
#     # convert URIs to absolute system paths
#     if uri.startswith(mUrl):
#         path = os.path.join(mRoot, uri.replace(mUrl, ""))
#     elif uri.startswith(sUrl):
#         path = os.path.join(sRoot, uri.replace(sUrl, ""))
#     else:
#         return uri  # handle absolute uri (ie: http://some.tld/foo.png)
#
#     # make sure that file exists
#     if not os.path.isfile(path):
#             raise Exception(
#                 'media URI must start with %s or %s' % (sUrl, mUrl)
#             )
#     return path
#
#
# def render_pdf_view(request):
#     template_path = 'user_printer.html'
#     context = {'myvar': 'this is your template context'}
#     # Create a Django response object, and specify content_type as pdf
#     response = HttpResponse(content_type='application/pdf')
#     response['Content-Disposition'] = 'attachment; filename="report.pdf"'
#     # find the template and render it.
#     template = get_template(template_path)
#     html = template.render(Context(context))
#
#     # create a pdf
#     pisaStatus = pisa.CreatePDF(
#        html, dest=response, link_callback=link_callback)
#     # if error then show some funy view
#     if pisaStatus.err:
#        return HttpResponse('We had some errors <pre>' + html + '</pre>')
#     return response
from orphanage.utils import get_scholar_year


class StudentCardPDF(PDFTemplateView):

    cmd_options = {
        'page-width': '140',
        'page-height': '80',
        'orientation': 'portrait',
        'margin-top': 0,
        'margin-bottom': 0,
        'margin-left': 0,
        'margin-right': 0,
    }

    filename = None

    template_name = 'orphanage/pdf/student_card.html'

    context = {}

    def get(self, request, *args, **kwargs):

        if 'student_id' in kwargs:
            students = Student.objects.filter(pk=kwargs['student_id'])
            if not students:
                raise Http404()
            student_title = 'التلميذ' if students[0].sex == 'm' else 'التلميذة'
            messages.success(request, 'لقد تمت طباعة بطاقة ' + student_title + ' بنجاح.')
        else:
            if 'students_ids' in kwargs:
                students = Student.objects.filter(id__in=kwargs['students_ids'])
            else:
                students = Student.objects.all()
            messages.success(request, 'تمت طباعة بطاقات الأطفال بنجاح.')

        self.context['students'] = students
        self.context['scholar_year'] = get_scholar_year(switch_month=6)

        if request.GET.get('as', '') == 'html':
            return TemplateResponse(
                request=request, template=self.template_name, context=self.context,
            )

        return PDFTemplateResponse(
            request=request, template=self.template_name, filename=self.filename, context=self.context,
            show_content_in_browser=False, cmd_options=self.cmd_options,
        )

orphanage/templates/orphanage/grade/grade_details.html
{% extends 'orphanage/base.html' %}
{% load static %}


{% block extra_css %}
    <style>
        .inner-nav ul {
            list-style: none;
        }
    </style>
{% endblock extra_css %}


{% block header_actions %}  
    <div class="btn-group float-md-right" role="group" aria-label="Button group with nested dropdown">
        <div class="btn-group" role="group">
            <button class="btn btn-outline-primary dropdown-toggle dropdown-menu-left" id="btnGroupDrop1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="ft-more-vertical icon-left"></i> المزيد
            </button>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="btnGroupDrop1" style="width: 175px;">
                <a class="dropdown-item" onclick="delete_grade()">مسح المستوى الدراسي</a>
            </div>
        </div>
        <a class="btn btn-outline-primary" href="{% url 'orphanage:grade_insert' %}"><i class="ft-plus"></i></a>
        <a class="btn btn-outline-primary" href="{% url 'orphanage:grade_update' grade.id %}"><i class="ft-edit"></i></a>
    </div>
{% endblock header_actions %}


{% block  content_body %}

    <section id="javascript">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collpase show">
                        <div class="card-body card-dashboard">
                            <div class="container-fluid dt-bootstrap4 no-footer">
                                <div class="container">
                                    <div class="grade-menu">
                                        <div class="row mb-5">
                                            <!-- <div class="col-xl-4 col-lg-6 col-12">
                                                <div class="card">
                                                    <div class="card-content">
                                                        <a href="{% url 'orphanage:students' grade.id %}" class="text-white">
                                                            <div class="media align-items-stretch">
                                                                <div class="p-2 text-center bg-primary bg-darken-2">
                                                                    <i class="ft-users font-large-2 white"></i>
                                                                </div>
                                                                <div class="p-2 bg-gradient-x-primary white media-body">
                                                                    <h2>لائحة التلاميذ</h2>
                                                                    <h3 class="text-bold-400 mb-0">{{ students_count }}</h3>
                                                                </div>
                                                            </div>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div> -->
                                            <div class="col-12 inner-nav">
                                                <ul class="p-0">
                                                    <li><a class="btn btn-dark" href="{% url 'orphanage:students' grade.id %}">لائحة التلاميذ</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="subjects">
                                        <h1 class="font-weight-bold d-flex align-items-center">
                                            <span>لائحة المواد الدراسية</span>
                                            <button type="button" class="btn btn-outline-success font-weight-bold ml-2" data-toggle="modal" data-target="#subject-creation-modal">إضافة مادة دراسية</button>
                                        </h1>
                                        <table class="table table-striped table-bordered">
                                            <thead class="thead-active">
                                                <tr class="rtl">
                                                    <th scope="col">إسم المادة</th>
                                                    <th scope="col">رقم المادة</th>
                                                    <th scope="col">المعامل</th>
                                                    <th scope="col"></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for subject in subjects %}
                                                    <tr class="rtl">
                                                        <th><h3>{{ subject.title }}</h3></th>
                                                        <td>{{ subject.code }}</td>
                                                        <td>{{ subject.coeff }}</td>
                                                        <td>
                                                            <div class="btn-group" role="group">
                                                                <button class="btn btn-outline-primary dropdown-toggle dropdown-menu-left" id="btnGroupDrop1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                                    <i class="ft-more-vertical"></i>
                                                                </button>
                                                                <div class="dropdown-menu dropdown-menu-left" aria-labelledby="btnGroupDrop1" style="width: 175px;">
                                                                    <a class="dropdown-item" onclick="delete_subject({{ subject.id }})">مسح المادة الدراسية</a>
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content_body %}


{% block modals %}
<div class="modal fade text-left" id="subject-creation-modal" tabindex="-1" role="dialog" aria-labelledby="subjectCreationModal" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="subject_creation_form" method="POST">
                {% csrf_token %}
                <input type="hidden" name="action" value="create_subject">
                <div class="modal-header">
                    <h4 class="modal-title text-center" id="myModalLabel2">إضافة مادة دراسية</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="font-weight-bold" for="id_title">{{ subject_form.title.label }}</label>
                        {{ subject_form.title }}
                        {% if subject_form.title.errors %}
                            <div class="invalid-feedback">
                                {{ subject_form.title.errors }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="font-weight-bold" for="id_code">{{ subject_form.code.label }}</label>
                        {{ subject_form.code }}
                        {% if subject_form.code.errors %}
                            <div class="invalid-feedback">
                                {{ subject_form.code.errors }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="font-weight-bold" for="id_coeff">{{ subject_form.coeff.label }}</label>
                        {{ subject_form.coeff }}
                        {% if subject_form.coeff.errors %}
                            <div class="invalid-feedback">
                                {{ subject_form.coeff.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="modal-footer justify-content-start">
                    <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">إلغاء</button>
                    <button type="submit" class="btn btn-outline-primary">إضافة</button>
                </div>
            </form>
        </div>
    </div>
  </div>
{% endblock modals %}


{% block extra_js %}

    <script>
        // Global vars
        let csrf_token = '{% csrf_token %}';

        // Functions
        function delete_grade() {
            delete_instance('هل أنت متأكد من مسح المستوى الدراسي ؟');
        }

        // Functions
        function delete_subject( subject_id ) {
            delete_instance('هل أنت متأكد من مسح هذه المادة الدراسية ؟', 'delete_subject', subject_id);
        }
    </script>

    <script src="{% static 'orphanage/js/crud_functions.js' %}"></script>

{% endblock extra_js %}

orphanage/templates/orphanage/grade/grade_update.html
{% extends 'orphanage/base.html' %}
{% load staticfiles %}

{% block stylesheets %}

    <!-- Daterangepicker CSS -->
    <link href="{% static 'orphanage/vendors/daterangepicker/daterangepicker.css' %}" rel="stylesheet" type="text/css" />

{% endblock stylesheets %}

{% block  content_body %}
    <div class="page-content">

        <div class="hk-pg-header pt-4 mb-0">
            <h4 class="hk-pg-title rtl font-weight-bold w-100 justify-content-end pr-4 pt-2 pb-0">
                {% if form.instance.id %}
                    تحديث بيانات المستوى الدراسي
                {% else %}
                    إضافة مستوى دراسي
                {% endif %}
            </h4>
        </div>

        <div class="container mt-3">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row infos rtl">
                    <div class="col-md-6 col-12">
                        <div class="form-group">
                            <label class="font-weight-bold" for="id_level">{{ form.level.label }}</label>
                            {{ form.level }}
                            {% if form.level.errors %}
                                <div class="invalid-feedback">
                                    {{ form.level.errors }}
                                </div>
                            {% endif %}
                        </div>

                        <hr>
                        <a class="btn btn-default font-weight-bold" href="{% if form.instance.id %}{%  url 'orphanage:grade_details' form.instance.id %}{% else %}{%  url 'orphanage:grades' %}{% endif %}">
                            إلغاء
                        </a>
                        <button class="btn btn-primary font-weight-bold" type="submit">{% if form.instance.id %}تحديث{% else %}إضافة{% endif %}</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
{% endblock content_body %}

{% block js %}

    <!-- Daterangepicker JavaScript -->
    <script src="{% static 'orphanage/vendors/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'orphanage/vendors/daterangepicker/daterangepicker.js' %}"></script>

    <script>
        let datepickers = $('input[role="datepicker"]');

        datepickers.daterangepicker({
            "singleDatePicker": true,
            "autoApply": false,
            "locale": {
                "format": "DD/MM/YYYY",
                "separator": " - ",
                "daysOfWeek": [
                    "Lu",
                    "Ma",
                    "Me",
                    "Je",
                    "Ve",
                    "Sa",
                    "Di"
                ],
                "monthNames": [
                    "Janvier",
                    "Février",
                    "Mars",
                    "Avril",
                    "Mai",
                    "Juin",
                    "Juillet",
                    "Août",
                    "Septembre",
                    "Octobre",
                    "Novembre",
                    "Décembre"
                ],
            },
            "startDate": "{% if form.instance.id %}{{ form.instance.birthday|date:'d/m/Y' }}{% else %}01/01/2000{% endif %}",
            "endDate": parseInt(moment().format('YYYY'), 10),
            "opens": "left",
        });
    </script>

{% endblock js %}